### ISSUE TITLE
SQL Mapper find() does not return virual fields and throws an error when using options

### ISSUE THREAD

**Issue by larsbrandi** [bcosca/fatfree#757]
Testing 3.4.0 vs 3.3.0 find() does not behave as expected. Virtual fields is not returned for find() but fields retrieved from the db is.

Defining an option like :

```
find(array('ordno=?',$ordID),array('group'=>'date'));
```
throws an error
```
[Sun Jan  4 14:00:10 2015] PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JOIN (SELECT `date` FROM `timesheet_readable` GROUP BY `date`) AS `sub` ON' at line 1
[Sun Jan  4 14:00:10 2015] - lib/db/sql/mapper.php:262 DB\SQL->exec()
[Sun Jan  4 14:00:10 2015] - lib/db/sql/mapper.php:302 DB\SQL\Mapper->select()
[Sun Jan  4 14:00:10 2015] - app/models/Costings1.php:24 DB\SQL\Mapper->find()
```
select() does not return any result in a function like this : 
```
public function find_operations() {
	$prod=new DB\SQL\Mapper($this->db,'Product');
	$prod->set('part_productID','id');
	return $prod->select('id AS part_productID,descr,prodno,prodtype,descr',array('prodtype=? OR prodtype=?','o','oc'));
}
```
This was the findings from test of 3.4.0 from 3.3.0

**Comment by larsbrandi** [comment]
Inserted echo $sql; on line 262

The table 'timesheet_readable' is a view

```
find(array('ordno=?',$ordID)); 
``` 
gives
```
SELECT `Rules`.`id`,`Rules`.`category`,`Rules`.`descr`,`Rules`.`value`,`Rules`.`parameters` FROM `Rules` WHERE descr=? AND category=?SELECT `Ord`.`id`,`Ord`.`customerID`,`Ord`.`ordno`,`Ord`.`invoice_sum`,`Ord`.`status`,`Ord`.`date`,`Ord`.`deliverydate`,`Ord`.`date_finished`,(UNIX_TIMESTAMP(MAX(date))) AS `maxdate` FROM `Ord`SELECT `timesheet_readable`.`id`,`timesheet_readable`.`date`,`timesheet_readable`.`time`,`timesheet_readable`.`userID`,`timesheet_readable`.`surname`,`timesheet_readable`.`lastname`,`timesheet_readable`.`ordno`,`timesheet_readable`.`customer`,`timesheet_readable`.`custno`,`timesheet_readable`.`operation`,`timesheet_readable`.`o_salesprice`,`timesheet_readable`.`used_time`,`timesheet_readable`.`o_costings`,`timesheet_readable`.`c_productID`,`timesheet_readable`.`dim1`,`timesheet_readable`.`c_salesprice`,`timesheet_readable`.`consumableID`,`timesheet_readable`.`consumable`,`timesheet_readable`.`c_costings`,`timesheet_readable`.`photo`,`timesheet_readable`.`circ_time`,`timesheet_readable`.`circ_costings`,`timesheet_readable`.`prod_prodno`,`timesheet_readable`.`prod_descr`,`timesheet_readable`.`ordered_no`,`timesheet_readable`.`finished_no`,(SUM(o_costings)) AS `total_operation`,(SUM(c_costings)) AS `total_consumable`,(SUM(circ_costings)) AS `total_circ` FROM `timesheet_readable` WHERE ordno=?SELECT `Ord`.`id`,`Ord`.`customerID`,`Ord`.`ordno`,`Ord`.`invoice_sum`,`Ord`.`status`,`Ord`.`date`,`Ord`.`deliverydate`,`Ord`.`date_finished` FROM `Ord` WHERE ordno=? 
```
```
find(array('ordno=?',$ordID),array('group'=>'date'));
```
gives
```
SELECT `Rules`.`id`,`Rules`.`category`,`Rules`.`descr`,`Rules`.`value`,`Rules`.`parameters` FROM `Rules` WHERE descr=? AND category=?SELECT `Ord`.`id`,`Ord`.`customerID`,`Ord`.`ordno`,`Ord`.`invoice_sum`,`Ord`.`status`,`Ord`.`date`,`Ord`.`deliverydate`,`Ord`.`date_finished`,(UNIX_TIMESTAMP(MAX(date))) AS `maxdate` FROM `Ord`SELECT `timesheet_readable`.`id`,`timesheet_readable`.`date`,`timesheet_readable`.`time`,`timesheet_readable`.`userID`,`timesheet_readable`.`surname`,`timesheet_readable`.`lastname`,`timesheet_readable`.`ordno`,`timesheet_readable`.`customer`,`timesheet_readable`.`custno`,`timesheet_readable`.`operation`,`timesheet_readable`.`o_salesprice`,`timesheet_readable`.`used_time`,`timesheet_readable`.`o_costings`,`timesheet_readable`.`c_productID`,`timesheet_readable`.`dim1`,`timesheet_readable`.`c_salesprice`,`timesheet_readable`.`consumableID`,`timesheet_readable`.`consumable`,`timesheet_readable`.`c_costings`,`timesheet_readable`.`photo`,`timesheet_readable`.`circ_time`,`timesheet_readable`.`circ_costings`,`timesheet_readable`.`prod_prodno`,`timesheet_readable`.`prod_descr`,`timesheet_readable`.`ordered_no`,`timesheet_readable`.`finished_no`,(SUM(o_costings)) AS `total_operation`,(SUM(c_costings)) AS `total_consumable`,(SUM(circ_costings)) AS `total_circ` FROM `timesheet_readable` WHERE ordno=? JOIN (SELECT `date` FROM `timesheet_readable` GROUP BY `date`) AS `sub` ON 
```

**Comment by bcosca** [comment]
The SQL query for the `'group'` is truncated. I'll check.

**Comment by larsbrandi** [comment]
It's a view, but 'id' is the primary key in the underlying table

**Comment by bcosca** [comment]
Sorry, I posed an irrelevant question. Views don't have primary keys. Can you test the latest commit? Let me know if it works.

**Comment by larsbrandi** [comment]
I'm not that used to git :-) but the latest commit I can find right now is 4 days old both in dev and master.

**Comment by bcosca** [comment]
I'll fix this repo later. You can go to: https://github.com/bcosca/fatfree-core

**Comment by larsbrandi** [comment]
```
find(array('ordno=?',$ordID),array('group'=>'date'));
```
don't throw an error any longer.

Virtual fields still don't display like defined here :

```
	 public function result_tot($ordID) {
		
		$this->total_operation='SUM(o_costings)';
		$this->total_consumable='SUM(c_costings)';
		$this->total_circ='SUM(circ_costings)';		
		return $this->find(array('ordno=?',$ordID));
	 }
```

**Comment by ikkez** [comment]
@bcosca in your comment at https://github.com/bcosca/fatfree-core/commit/dea065d2595127039e03078fd1c0a199ed1bc677 you have the virtual fields itself as part of the sub-join that does the grouping. I think that's correct but the current implementation doesn't seem to do it like this:
```
SELECT t2.field1, t2.field2, t1.ae1, t1.ae2... FROM
    (SELECT pkey1, aggregate_expr1 as ae1, aggregate_expr2 as ae2, ...
        FROM table
        GROUP BY aggregate_field1, aggregate_field2,... ) AS t1
    JOIN table AS t2 ON t1.pkey1=t2.pkey1,...;
```

**Comment by bcosca** [comment]
@xfra35 is right. I've given this some thought, and it seems the JOIN code is far more complex than it appears initially. So with respect to fatfree-core/commit/dea065d, I am reverting to the previous behavior, taking the suggestion of @xfra35 to restrict the previous algorithm to mysql and sqlite, while limiting the fields retrieved for other engines. See latest commit.

**Comment by larsbrandi** [comment]
Does this mean I have to stick to 3.3.0 until this is resolved ? Tried the latest fatfree-core, and virtual fields dosen't show up, and select() don't pass fields named with 'AS'.

**Comment by bcosca** [comment]
Hang on. If it isn't resolved, we can reopen it.

**Comment by bcosca** [comment]
Let's be precise here. What mapper commands did you issue that don't handle the virtual fields? The SQL query of each mapper command would help.

**Comment by bcosca** [comment]
Does this settle the issue?

**Comment by xfra35** [comment]
There's still a parenthesis missing so that the adhoc fields could be appended in every case:
```php
return $this->select(
	($options['group'] && !preg_match('/mysql|sqlite/',$this->engine)?
		$options['group']:
		implode(',',array_map(array($this->db,'quotekey'),
			array_keys($this->fields)))).$adhoc,$filter,$options,$ttl);
```

**Comment by bcosca** [comment]
Done.

**Comment by larsbrandi** [comment]
Just tested the latest commit. And the issue persist. So to clarify things, I have tested three cases.
Case 1 without 'group' : 
```
		$this->total_operation='SUM(o_costings)';
		$this->total_consumable='SUM(c_costings)';
		$this->total_circ='SUM(circ_costings)';		
		return $this->find(array('ordno=?',$ordID));
```
The three declared virtual fields dosen't show up. I can retrieve fields from the table.

Case 2 with 'group' clause : 

```
		$this->total_operation='SUM(o_costings)';
		$this->total_consumable='SUM(c_costings)';
		$this->total_circ='SUM(circ_costings)';		
		return $this->find(array('ordno=?',$ordID),array('group'=>'date'));
```
The three declared virtual fields dosen't show up. I can retrieve fields from the table.

Case 3 using select() instead of find() : 
```
		$this->set('total_operation','SUM(o_costings)');
		$this->set('total_consumable','SUM(c_costings)');
		$this->set('total_circ','SUM(circ_costings)');
		return $this->select('id,SUM(o_costings) AS total_operation,SUM(c_costings) AS total_consumable,SUM(circ_costings) AS total_circ',array('ordno=?',$ordID),array('group'=>'date'));
```
Returns only 'id', none of the SUM().

Case 1,2,3 done with 'lib' from 3.3.0 produce a correct output

**Comment by ikkez** [comment]
@larsbrandi which DB engine do you use? MySQL?

**Comment by xfra35** [comment]
@larsbrandi I just made the following test with the latest commit (https://github.com/bcosca/fatfree-core/commit/095189db7485a052c065fd07f38ff9c0750e0e4b):
```php
$f3->route('GET /testdb',function($f3){
  $db=new DB\SQL('mysql:host=127.0.0.1;port=3306;dbname=test','root','tincouch');
  // table creation:
  $sql='CREATE TABLE IF NOT EXISTS `orders` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `customer` int(10) unsigned NOT NULL,
	`stamp` int(10) unsigned NOT NULL,
	 PRIMARY KEY (`id`));';
  $db->exec($sql);
  $sql="REPLACE INTO `orders` (`id`, `customer`, `stamp`) VALUES
  (1, 10, 1420560000),(2, 20, 1420570000),(3, 10, 1420580000),
  (4, 10, 1420590000),(5, 10, 1420600000),(6, 20, 1420610000)";
  $db->exec($sql);
  // orders grouped by customer:
  $mapper=new DB\SQL\Mapper($db,'orders');
  $mapper->set('nb_orders','COUNT(*)');
  $mapper->set('last_date','MAX(stamp)');
  $rows=$mapper->find('',array('group'=>'customer','order'=>'customer'));
  foreach($rows as $row)
    echo "$row->customer,$row->nb_orders,$row->last_date<br>";
});
```
Everything works fine here. It should output:
```
10,4,1420600000
20,2,1420610000
```

Are you sure you fetched the latest commit of the [fatfree-core](https://github.com/bcosca/fatfree-core) repository? If yes, can you please provide a sample of code easily reproducible?

**Comment by ikkez** [comment]
Sorry, my bad. I meant the first array element of course:
  `var_dump($this->f3->get('costs.0')->cast());`

**Comment by larsbrandi** [comment]
Here is a screenshot with 3.3.0 lib and output of var_dump($this->f3->get('costs.0')->cast()); in top : 

![screenshot from 2015-01-07 07 35 50](https://cloud.githubusercontent.com/assets/4633457/5641840/17c5da40-9640-11e4-9c46-47566b950614.png)

And for latest commit lib : 

![screenshot from 2015-01-07 07 37 26](https://cloud.githubusercontent.com/assets/4633457/5641866/8f0de2dc-9640-11e4-83d0-a2c7cea28df3.png)

**Comment by larsbrandi** [comment]
Output of cast() with 3.3.0 lib first and latest commit : 
```
array(29) { ["id"]=> NULL ["date"]=> string(10) "2014-10-29" ["time"]=> NULL ["userID"]=> NULL ["surname"]=> NULL ["lastname"]=> NULL ["ordno"]=> NULL ["customer"]=> NULL ["custno"]=> NULL ["operation"]=> NULL ["o_salesprice"]=> NULL ["used_time"]=> NULL ["o_costings"]=> NULL ["c_productID"]=> NULL ["dim1"]=> NULL ["c_salesprice"]=> NULL ["consumableID"]=> NULL ["consumable"]=> NULL ["c_costings"]=> NULL ["photo"]=> NULL ["circ_time"]=> NULL ["circ_costings"]=> NULL ["prod_prodno"]=> NULL ["prod_descr"]=> NULL ["ordered_no"]=> NULL ["finished_no"]=> NULL ["total_operation"]=> string(8) "610.9650" ["total_consumable"]=> NULL ["total_circ"]=> NULL } 
array(29) { ["id"]=> int(342) ["date"]=> string(10) "2014-10-29" ["time"]=> string(5) "19.03" ["userID"]=> int(1) ["surname"]=> string(4) "John" ["lastname"]=> string(6) " Smith" ["ordno"]=> int(10273) ["customer"]=> string(16) "Q. P. Audit Firm" ["custno"]=> string(3) "104" ["operation"]=> string(19) "Consulting services" ["o_salesprice"]=> string(5) "81.00" ["used_time"]=> string(6) "0.0225" ["o_costings"]=> string(6) "1.8225" ["c_productID"]=> NULL ["dim1"]=> NULL ["c_salesprice"]=> NULL ["consumableID"]=> NULL ["consumable"]=> NULL ["c_costings"]=> NULL ["photo"]=> string(14) "1414605811.jpg" ["circ_time"]=> NULL ["circ_costings"]=> NULL ["prod_prodno"]=> string(3) "101" ["prod_descr"]=> string(18) "Desktop GZ 1.0 Pro" ["ordered_no"]=> int(4) ["finished_no"]=> string(6) "0.0000" ["total_operation"]=> string(8) "610.9650" ["total_consumable"]=> NULL ["total_circ"]=> NULL } 
```

**Comment by ikkez** [comment]
Nice. So it looks to me that everything in working now. Can you confirm that?

**Comment by larsbrandi** [comment]
No. I can't display any of the virtual fields i.e. total_operation, total_consumable and total_circ. All other fields can be displayed, using <repeat></repeat>.

**Comment by ikkez** [comment]
I see that total_operation is successfully populated

**Comment by larsbrandi** [comment]
Yes. And using the 3.3.0 it is displayed, but using the new commit, everything else is displayed but the three virtual fields.

**Comment by ikkez** [comment]
i can't get my head around this. It's working nice here in the latest commit, and if the example from @xfra35 is working for you, it somehow proved that it is basically working on your side too. 
The essence is: When you add virtual fields that contains an aggregate function, you should add a group option too. There are db engines, that do only return the grouped and aggregated fields, when a group action was made.

**Comment by larsbrandi** [comment]
My controller code is : 
```PHP
	public function result()
	{
		$costs = new Costings1($this->db);
		$erp = new Economic($this->db);
		$erp->create_temp_Ord();
		$erp->orders();
		
		$costs->total_operation='SUM(o_costings)';
		$costs->total_consumable='SUM(c_costings)';
		$costs->total_circ='SUM(circ_costings)';
//		$rows=$costs->result_tot($this->f3->get('POST.ordID'))
		$this->f3->set('costs',$costs->find(array('ordno=?',$this->f3->get('POST.ordID')),array('group'=>'date')));
		var_dump($this->f3->get('costs.0')->cast());
//		$costs->find(array('ordno=?',$this->f3->get('POST.ordID')));
//		var_dump($costs->cast());
//		$rows=$costs->find(array('ordno=?',$this->f3->get('POST.ordID')),array('group'=>'date'));
//		foreach($rows as $row){
//		echo "$row->total_operation,$row->total_consumable<br>";}
//		$this->f3->set('costs',$costs->result_tot($this->f3->get('POST.ordID')));
//		var_dump($this->f3->get('costs'));
		$ordersum = new DB\SQL\Mapper($this->db,'Ord');
		$this->f3->set('ordersum',$ordersum->load(array('ordno=?',$this->f3->get('POST.ordID'))));
        $this->f3->set('page_head',$this->f3->get('costings'));
        $this->f3->set('message', $this->f3->get('PARAMS.message'));
        $this->f3->set('view','/costing/list_1.htm');		
	}
```
list_1.htm for my view is : 

```HTML+PHP
<form action="{{ @BASE.'/cost/result1' }}" method="post">
		<a href="{{ @BASE.'/download/costing/'. @POST[ordID] }}">
			<button type="button" class="btn btn-info">Download som regneark</button>
		</a>

<h3><B>{{@operations_for_ordre}}   {{@ordersum[ordno]}} <check if="{{ @activity==1}}"><true>{{@active}}</true></check></B><BR></h3>


<repeat group="{{ @costs }}" value="{{ @lines }}">
	Dato : {{@lines[date]}}<br>

<table class="table table-hover table-striped table-bordered">
	<th scope="col">{{@operation}}</th>
	<td><div align="right">{{ number_format(@lines[total_operation], 2, ',', '.') }}</div></td>
	<check if="{{ @lines[total_circ]>0 }}">
	<tr>
	<th scope="col">{{@t_oc_operation}}</th>
	<td><div align="right">{{ number_format(@lines[total_circ], 2, ',', '.') }}</div></td>
	</tr>
	</check>
	<tr>
	<th scope="col">{{@consumable}}</th>
	<td><div align="right">{{ number_format(@lines[total_consumable], 2, ',', '.') }}</div></td>
	</tr>
	<check if="{{ @lines[total_circ]>0 }}">
	<tr>
	<th scope="col">{{@total}} circ</th>
	<td><div align="right">{{ number_format(@lines[total_circ]+@lines[total_consumable], 2, ',', '.') }}</div></td>
	</tr>
	</check>
	<tr>
	<th scope="col">{{@total}}</th>	
	<td><div align="right">{{ number_format(@lines[total_operation]+@lines[total_consumable], 2, ',', '.') }}</div></td>
	</tr>
	<tr>
	<th scope="col">{{@order_sum}}</th>	
	<td><div align="right">{{ number_format(@ordersum[invoice_sum], 2, ',', '.') }}</div></td>
	</tr>
	<check if="{{ @lines[total_circ]>0 }}">
	<tr>
	<th scope="col">{{@t_deviation}} circ</th>	
	<td><div align="right">{{ number_format((@lines[total_circ]+@lines[total_consumable])/@ordersum[invoice_sum]*100, 2, ',', '.') }} %</div></td>
	</tr>
	</check>
	<check if="{{ @ordersum[invoice_sum]>0 }}">
	<tr>
	<th scope="col">{{@t_deviation}}</th>	
	<td><div align="right">{{ number_format((@lines[total_operation]+@lines[total_consumable])/@ordersum[invoice_sum]*100, 2, ',', '.') }} %</div></td>
	</tr>
	</check>
</table>
</repeat>

    <div class="control-group">
        <div class="">
            <input type="hidden" name="create" value="create" />
            <input type="hidden" name="ordID" value="{{@POST[ordID]}}" />
            
            <button type="submit" class="btn btn-primary">{{@t_expand}}</button>
        </div>
    </div>

</form>
```
Maybe I am just staring me blind on something here. It should be straight forward. However the cast() shows a difference from 3.3.0 to now.

**Comment by xfra35** [comment]
@larsbrandi I just had a look at the results of your [cast](https://github.com/bcosca/fatfree/issues/757#issuecomment-68986786). The results are as expected:

**3.3.0**
```
date: "2014-10-29"
total_operation: "610.9650"
total_consumable: NULL
total_circ: NULL
other fields: NULL
```

**3.4.1**
```
date: "2014-10-29"
total_operation: "610.9650"
total_consumable: NULL
total_circ: NULL
other fields: random value
```

So it looks like the order you've picked up (orderid=10273) is containing invalid data (especially we have c_costings and circ_costings set to NULL).

**Comment by larsbrandi** [comment]
total_operation will always be positive, but it still prints 0 even if it is 610.9650 . I think this is the weird thing here. Making a straight ``` $db->exec('SELECT date,SUM(o_costings) AS total_operation,SUM(c_costings) AS total_consumable,SUM(circ_costings) AS total_circ FROM timesheet_readable WHERE ordno='.$ordID.' GROUP BY date ASC;'); ``` does present the data nicely even thought total_consumable and total_circ is NULL.

**Comment by xfra35** [comment]
So it looks like we misunderstood your problem. We thought that virtual fields were not returned but they actually are. The problem stands at displaying level.

Can you try the following in your controller:
```php
echo number_format($this->f3->get('costs.0')->total_operation,2,',','.');
```
and tell us what it outputs?

**Comment by bcosca** [comment]
BTW, instead of:

```
{{ number_format(@lines[total_circ], 2, ',', '.') }}
```

You can use this:

```
{{ '{0,number,decimal,2}',@lines.total_circ | format }}
```

**Comment by larsbrandi** [comment]
@xfra35 it returns 610,97

**Comment by xfra35** [comment]
then it should return the same in the template, try various alternatives to locate the problem:
```
{{ @lines->total_operation }}
{{ @lines.total_operation }}
{{ @lines[total_operation] }}
{{ number_format(@lines->total_operation, 2, ',', '.') }}
{{ number_format(@lines.total_operation, 2, ',', '.') }}
{{ number_format(@lines[total_operation], 2, ',', '.') }}
```

**Comment by larsbrandi** [comment]
It returns nothing. I have tried : 
```
	{{ @lines->total_operation }} test1<br>
	{{ @lines.total_operation }} test2<br>
	{{ @lines[total_operation] }} test3<br>
	{{ number_format(@lines->total_operation, 2, ',', '.') }} test4<br>
	{{ number_format(@lines.total_operation, 2, ',', '.') }} test5<br>
	{{ number_format(@lines[total_operation], 2, ',', '.') }} test6<br>
```
Replacing total_operation with fields from the table like surname or o_costings does display a value. Wierd.

**Comment by xfra35** [comment]
Pretty tricky bug you've discovered. It's actually related to the escaping functionality. Try to set `ESCAPE` to `FALSE` and it will work. I'm trying to narrow down the issue.

**Comment by larsbrandi** [comment]
Setting ESCAPE=FALSE. It works. Now it is possible to write nice looking code again :-)

**Comment by xfra35** [comment]
@ikkez narrowed down the issue to the mapper setter. Inside the `recursive()` method, we're having:
```php
foreach ($cast as $key=>$val)
  $arg->$key=$this->recursive(etc...
```
So in the case of a virtual field of a mapper, we end up **redefining** a new expression instead of modifying its value.

The problem didn't occur in 3.3.0 because `$cast` was empty (in other words, mapper values were not escaped).

**Comment by xfra35** [comment]
As a quick fix, we could prevent virtual fields from being overwritten:
```php
class Mapper extends \DB\Cursor {

  function set($key,$val) {
    //..
    if (!isset($this->adhoc[$key])) //<< fix here
      $this->adhoc[$key]=array('expr'=>'('.$val.')','value'=>NULL);
  }
```
Or we could modify the value on a second call instead of redefining the field:
```php
  function set($key,$val) {
    //..
    if (isset($this->adhoc[$key]))
      $this->adhoc[$key]['value']=$val;
    else
      $this->adhoc[$key]=array('expr'=>'('.$val.')','value'=>NULL);
  }
```

**Comment by bcosca** [comment]
Uhh, sorry I didn't quite get that. What is contained in the string the is being escaped?

**Comment by ikkez** [comment]
I think modifying the value on a second call is probably the easiest solution now and shouldn't hurt.

**Comment by ikkez** [comment]
Let us come back to this one. I think the [initial issue](https://github.com/bcosca/fatfree/issues/757#issue-53370371) regarding the faulty sql query when using a `group` option was already fixed here.
The remaining problem regarding the overwriting of virtual field values in the recursive-deep-copy-escaping-process is actually another issue. So maybe one of the solutions from @xfra35 could do the trick, or we open another issue to think about that once more in detail.

**Comment by xfra35** [comment]
I've opened a PR for this bug, so let's close this issue.
